FORMAT: 1A
HOST: http://sjsuconnect.apiblueprint.org/register

# SJSU Connect REST APIs

This API will register new user into the database and send a 4 digit verification code to registered email.

## Register [/register]

### Register New User [POST]

+ Request (application/json)

        {
            "first_name": "Sagar",
            "last_name": "Mane",
            "phone_number": "669-225-9371",
            "country_code": 1,
            "email": "sagar.mane@sjsu.edu",
            "password": "**"
        }

+ Response 200 (application/json)

        [
            {
                "verification_code":4444
            }
        ]
        
## Login [/login]

### Login Existing User [POST]

+ Request (application/json)

        {
            "email": "sagar.mane@sjsu.edu",
            "password": "****"
            
        }

+ Response 200 (application/json)

        [
            {
                "status":"SignIn Successful"
            }
        ]